# Makefile for touch-timeout daemon (modular version 2.0)
#
# Build modular C daemon with:
# - Separate compilation units for each module
# - Optional systemd support
# - Unit tests with mocking
# - Code coverage reporting

# Version management (single source of truth)
VERSION_MAJOR = 2
VERSION_MINOR = 0
VERSION_PATCH = 0

CC = gcc
CFLAGS = -O2 -Wall -Wextra -Wno-unused-parameter -std=c17 -D_POSIX_C_SOURCE=200809L -Iinclude
LDFLAGS =
TARGET = touch-timeout

# Detect OS - add mock includes for non-Linux systems
UNAME_S := $(shell uname -s)
ifneq ($(UNAME_S),Linux)
    CFLAGS += -I./tests/mocks
    $(info Building on $(UNAME_S) with mock headers)
endif

# Source files
SRC_DIR = src
SRCS = $(SRC_DIR)/main.c \
       $(SRC_DIR)/config.c \
       $(SRC_DIR)/display.c \
       $(SRC_DIR)/input.c \
       $(SRC_DIR)/state.c \
       $(SRC_DIR)/timer.c

OBJS = $(SRCS:.c=.o)

# Detect systemd availability
SYSTEMD_PKG := $(shell pkg-config --exists libsystemd && echo "yes")

ifeq ($(SYSTEMD_PKG),yes)
    CFLAGS += -DHAVE_SYSTEMD $(shell pkg-config --cflags libsystemd)
    LDFLAGS += $(shell pkg-config --libs libsystemd)
    $(info Building with systemd support)
else
    $(info Building without systemd support)
endif

# Installation paths
PREFIX = /usr
BINDIR = $(PREFIX)/bin
SYSTEMD_UNIT_DIR = /etc/systemd/system
CONFIG_DIR = /etc

.PHONY: all clean install uninstall test coverage version help

all: version $(TARGET)

# Display help information
help:
	@echo "Touch-timeout daemon build system (v$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH))"
	@echo ""
	@echo "Targets:"
	@echo "  make              - Build daemon binary"
	@echo "  make version      - Generate version.h from VERSION_* variables"
	@echo "  make test         - Run unit tests"
	@echo "  make coverage     - Generate code coverage report"
	@echo "  make install      - Install daemon, systemd service, and config"
	@echo "  make uninstall    - Remove installed files (preserves config)"
	@echo "  make clean        - Remove build artifacts"
	@echo "  make help         - Display this help message"
	@echo ""
	@echo "Configuration:"
	@echo "  PREFIX            - Installation prefix (default: /usr)"
	@echo "  SYSTEMD_UNIT_DIR  - Systemd service directory (default: /etc/systemd/system)"
	@echo "  CONFIG_DIR        - Config file directory (default: /etc)"
	@echo ""
	@echo "Build flags:"
	@echo "  CFLAGS            - C compiler flags (default: -O2 -Wall -std=c17)"
	@echo "  CC                - C compiler (default: gcc)"
	@echo ""
	@echo "Systemd support: $(if $(SYSTEMD_PKG),enabled,disabled - install libsystemd-dev)"

# Generate version.h from VERSION_* variables
version:
	@mkdir -p include
	@echo "/**" > include/version.h
	@echo " * @file version.h" >> include/version.h
	@echo " * @brief Version information for touch-timeout daemon" >> include/version.h
	@echo " *" >> include/version.h
	@echo " * This file is auto-generated by the Makefile during build." >> include/version.h
	@echo " * Do not edit manually - modify VERSION_* variables in Makefile instead." >> include/version.h
	@echo " */" >> include/version.h
	@echo "" >> include/version.h
	@echo "#ifndef VERSION_H" >> include/version.h
	@echo "#define VERSION_H" >> include/version.h
	@echo "" >> include/version.h
	@echo "#define VERSION_MAJOR $(VERSION_MAJOR)" >> include/version.h
	@echo "#define VERSION_MINOR $(VERSION_MINOR)" >> include/version.h
	@echo "#define VERSION_PATCH $(VERSION_PATCH)" >> include/version.h
	@echo "#define VERSION_STRING \"$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH)\"" >> include/version.h
	@echo "" >> include/version.h
	@echo "#endif  // VERSION_H" >> include/version.h

# Build main binary
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

# Pattern rule for object files
%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

# Dependencies (headers)
$(SRC_DIR)/main.o: $(SRC_DIR)/config.h $(SRC_DIR)/display.h $(SRC_DIR)/input.h $(SRC_DIR)/state.h $(SRC_DIR)/timer.h include/version.h
$(SRC_DIR)/config.o: $(SRC_DIR)/config.h
$(SRC_DIR)/display.o: $(SRC_DIR)/display.h $(SRC_DIR)/config.h
$(SRC_DIR)/input.o: $(SRC_DIR)/input.h
$(SRC_DIR)/state.o: $(SRC_DIR)/state.h
$(SRC_DIR)/timer.o: $(SRC_DIR)/timer.h

# Clean build artifacts
clean:
	rm -f $(TARGET) $(OBJS)
	rm -f include/version.h
	$(MAKE) -C tests clean

# Run unit tests
test:
	$(MAKE) -C tests test

# Generate coverage report
coverage:
	$(MAKE) -C tests coverage

# Install to system
install: $(TARGET)
	install -D -m 755 $(TARGET) $(DESTDIR)$(BINDIR)/$(TARGET)
	install -D -m 644 systemd/touch-timeout.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/touch-timeout.service
	install -D -m 644 config/touch-timeout.conf $(DESTDIR)$(CONFIG_DIR)/touch-timeout.conf
	@echo "Installation complete. To enable service:"
	@echo "  sudo systemctl daemon-reload"
	@echo "  sudo systemctl enable touch-timeout.service"
	@echo "  sudo systemctl start touch-timeout.service"

# Uninstall from system
uninstall:
	systemctl stop touch-timeout.service 2>/dev/null || true
	systemctl disable touch-timeout.service 2>/dev/null || true
	rm -f $(DESTDIR)$(BINDIR)/$(TARGET)
	rm -f $(DESTDIR)$(SYSTEMD_UNIT_DIR)/touch-timeout.service
	@echo "Uninstallation complete. Config file preserved at $(CONFIG_DIR)/touch-timeout.conf"
