# Makefile for touch-timeout daemon
#
# Simplified 2-module architecture:
# - main.c: CLI, device I/O, event loop
# - state.c: Pure state machine (no I/O)
# - Optional systemd support

# Version management (single source of truth)
VERSION_MAJOR = 0
VERSION_MINOR = 7
VERSION_PATCH = 0
VERSION = $(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH)

CC = gcc
CFLAGS = -O2 -Wall -Wextra -Wno-unused-parameter -std=c99 -D_GNU_SOURCE -Iinclude
LDFLAGS =
BUILD_DIR = build
TARGET = $(BUILD_DIR)/touch-timeout-$(VERSION)-native

# Source files
SRC_DIR = src
SRCS = $(SRC_DIR)/main.c \
       $(SRC_DIR)/state.c

OBJS = $(SRCS:.c=.o)

# Detect systemd availability
SYSTEMD_PKG := $(shell pkg-config --exists libsystemd && echo "yes")

ifeq ($(SYSTEMD_PKG),yes)
    CFLAGS += -DHAVE_SYSTEMD $(shell pkg-config --cflags libsystemd)
    LDFLAGS += $(shell pkg-config --libs libsystemd)
    $(info Building with systemd support)
else
    $(info Building without systemd support)
endif

# Installation paths
PREFIX = /usr
BINDIR = $(PREFIX)/bin
SYSTEMD_UNIT_DIR = /etc/systemd/system

.PHONY: all clean install uninstall test coverage version help arm32 arm64 clean-all deploy-arm32 deploy-arm64 rollback-list rollback

all: version $(BUILD_DIR) $(TARGET)

# Display help information
help:
	@echo "Touch-timeout daemon build system (v$(VERSION))"
	@echo ""
	@echo "Build:"
	@echo "  make                 - Build for native platform"
	@echo "  make arm32           - Cross-compile for ARM 32-bit (RPi)"
	@echo "  make arm64           - Cross-compile for ARM 64-bit (RPi4)"
	@echo ""
	@echo "Deploy to RPi:"
	@echo "  make deploy-arm64 RPI=<ip>              - Build + deploy + install"
	@echo "  make deploy-arm64 RPI=<ip> MANUAL=1     - Build + deploy only"
	@echo "  make deploy-arm64 RPI=<ip> RPI_USER=pi  - Deploy as non-root user"
	@echo ""
	@echo "Rollback:"
	@echo "  make rollback-list RPI=<ip>             - List installed versions"
	@echo "  make rollback RPI=<ip> TO=X.Y.Z         - Rollback to specific version"
	@echo ""
	@echo "Local (on RPi):"
	@echo "  make install         - Install with versioned binary + symlink"
	@echo "  make uninstall       - Remove all versions and service"
	@echo ""
	@echo "Other:"
	@echo "  make test            - Run unit tests"
	@echo "  make coverage        - Generate coverage report"
	@echo "  make clean           - Remove build artifacts"
	@echo ""
	@echo "Output: $(BUILD_DIR)/touch-timeout-$(VERSION)-{native,arm32,arm64}"

# Cross-compilation targets for ARM
arm32: version $(BUILD_DIR)
	$(MAKE) clean-objs
	$(MAKE) CC=arm-linux-gnueabihf-gcc CFLAGS="-O2 -Wall -Wextra -Wno-unused-parameter -std=c99 -D_GNU_SOURCE -Iinclude -march=armv7-a -mfpu=neon" TARGET=$(BUILD_DIR)/touch-timeout-$(VERSION)-arm32 all

arm64: version $(BUILD_DIR)
	$(MAKE) clean-objs
	$(MAKE) CC=aarch64-linux-gnu-gcc CFLAGS="-O2 -Wall -Wextra -Wno-unused-parameter -std=c99 -D_GNU_SOURCE -Iinclude -march=armv8-a" TARGET=$(BUILD_DIR)/touch-timeout-$(VERSION)-arm64 all

# Deploy targets (require RPI=<ip>)
deploy-arm32:
	@test -n "$(RPI)" || { echo "Usage: make deploy-arm32 RPI=<ip>"; exit 1; }
	$(MAKE) arm32
	scripts/deploy.sh $(RPI) $(BUILD_DIR)/touch-timeout-$(VERSION)-arm32

deploy-arm64:
	@test -n "$(RPI)" || { echo "Usage: make deploy-arm64 RPI=<ip>"; exit 1; }
	$(MAKE) arm64
	scripts/deploy.sh $(RPI) $(BUILD_DIR)/touch-timeout-$(VERSION)-arm64

# Rollback targets (require RPI=<ip>)
RPI_USER ?= root

rollback-list:
	@test -n "$(RPI)" || { echo "Usage: make rollback-list RPI=<ip>"; exit 1; }
	@echo "Installed versions on $(RPI):"
	@ssh $(RPI_USER)@$(RPI) "ls -1 /usr/bin/touch-timeout-*-* 2>/dev/null || echo '  (none found)'"
	@echo ""
	@echo "Current: $$(ssh $(RPI_USER)@$(RPI) 'readlink /usr/bin/touch-timeout 2>/dev/null || echo "(not installed)"')"

rollback:
	@test -n "$(RPI)" || { echo "Usage: make rollback RPI=<ip> TO=X.Y.Z"; exit 1; }
	@test -n "$(TO)" || { echo "TO=<version> required. Run: make rollback-list RPI=$(RPI)"; exit 1; }
	@echo "Rolling back to version $(TO)..."
	ssh $(RPI_USER)@$(RPI) "ls /usr/bin/touch-timeout-$(TO)-* >/dev/null 2>&1 || { echo 'Version $(TO) not found'; exit 1; }"
	ssh $(RPI_USER)@$(RPI) "ln -sf /usr/bin/touch-timeout-$(TO)-* /usr/bin/touch-timeout && systemctl restart touch-timeout"
	@echo "Rollback complete. Current: $$(ssh $(RPI_USER)@$(RPI) 'readlink /usr/bin/touch-timeout')"

# Generate version.h from VERSION_* variables
version:
	@mkdir -p include
	@echo "/**" > include/version.h
	@echo " * @file version.h" >> include/version.h
	@echo " * @brief Version information for touch-timeout daemon" >> include/version.h
	@echo " *" >> include/version.h
	@echo " * This file is auto-generated by the Makefile during build." >> include/version.h
	@echo " * Do not edit manually - modify VERSION_* variables in Makefile instead." >> include/version.h
	@echo " */" >> include/version.h
	@echo "" >> include/version.h
	@echo "#ifndef VERSION_H" >> include/version.h
	@echo "#define VERSION_H" >> include/version.h
	@echo "" >> include/version.h
	@echo "#define VERSION_MAJOR $(VERSION_MAJOR)" >> include/version.h
	@echo "#define VERSION_MINOR $(VERSION_MINOR)" >> include/version.h
	@echo "#define VERSION_PATCH $(VERSION_PATCH)" >> include/version.h
	@echo "#define VERSION_STRING \"$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH)\"" >> include/version.h
	@echo "" >> include/version.h
	@echo "#endif  // VERSION_H" >> include/version.h

# Create build directory
$(BUILD_DIR):
	@mkdir -p $@

# Build main binary
$(TARGET): $(OBJS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

# Pattern rule for object files
%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

# Dependencies (headers)
$(SRC_DIR)/main.o: $(SRC_DIR)/state.h include/version.h
$(SRC_DIR)/state.o: $(SRC_DIR)/state.h

# Clean object files only (used between cross-compile targets)
clean-objs:
	rm -f $(OBJS)

# Clean build artifacts
clean:
	rm -f $(OBJS)
	rm -f $(BUILD_DIR)/touch-timeout-*
	rm -f include/version.h
	$(MAKE) -C tests clean

# Clean all artifacts including build directory
clean-all: clean
	rm -rf $(BUILD_DIR)

# Run unit tests
test:
	$(MAKE) -C tests test

# Generate coverage report
coverage:
	$(MAKE) -C tests coverage

# Install to system (versioned binary with symlink for rollback support)
install: $(TARGET)
	install -D -m 755 $(TARGET) $(DESTDIR)$(BINDIR)/touch-timeout-$(VERSION)-native
	ln -sf touch-timeout-$(VERSION)-native $(DESTDIR)$(BINDIR)/touch-timeout
	install -D -m 644 systemd/touch-timeout.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/touch-timeout.service
	@echo "Installation complete: $(BINDIR)/touch-timeout -> touch-timeout-$(VERSION)-native"
	@echo ""
	@echo "To enable service:"
	@echo "  sudo systemctl daemon-reload"
	@echo "  sudo systemctl enable --now touch-timeout.service"
	@echo ""
	@echo "To customize: sudo systemctl edit touch-timeout"

# Uninstall from system (removes all versions)
uninstall:
	systemctl stop touch-timeout.service 2>/dev/null || true
	systemctl disable touch-timeout.service 2>/dev/null || true
	rm -f $(DESTDIR)$(BINDIR)/touch-timeout
	rm -f $(DESTDIR)$(BINDIR)/touch-timeout-*-*
	rm -f $(DESTDIR)$(SYSTEMD_UNIT_DIR)/touch-timeout.service
	systemctl daemon-reload 2>/dev/null || true
	@echo "Uninstallation complete."
