/**
 * @file version.h
 * @brief Version information for touch-timeout daemon
 *
 * This file is auto-generated by the Makefile during build.
 * Do not edit manually - modify VERSION_* variables in Makefile instead.
 */

#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_STRING "2.0.0"

#endif  // VERSION_H
